// <auto-generated />
using System;
using HotBargainVbEx.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotBargainVbEx.Migrations
{
    [DbContext(typeof(HotBargainsDbContext))]
    [Migration("20210615124523_IdentityPackage")]
    partial class IdentityPackage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotBargainVbEx.Models.Personeel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VestigingId")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VestigingId");

                    b.ToTable("Personeelsleden");
                });

            modelBuilder.Entity("HotBargainVbEx.Models.Project", b =>
                {
                    b.Property<string>("ProjectNaam")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("HuidigBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjectNaam");

                    b.ToTable("Projecten");
                });

            modelBuilder.Entity("HotBargainVbEx.Models.Vestiging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vestigingen");
                });

            modelBuilder.Entity("PersoneelProject", b =>
                {
                    b.Property<string>("PersoneelsledenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectenProjectNaam")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PersoneelsledenId", "ProjectenProjectNaam");

                    b.HasIndex("ProjectenProjectNaam");

                    b.ToTable("PersoneelProject");
                });

            modelBuilder.Entity("HotBargainVbEx.Models.Personeel", b =>
                {
                    b.HasOne("HotBargainVbEx.Models.Vestiging", "Vestiging")
                        .WithMany()
                        .HasForeignKey("VestigingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vestiging");
                });

            modelBuilder.Entity("PersoneelProject", b =>
                {
                    b.HasOne("HotBargainVbEx.Models.Personeel", null)
                        .WithMany()
                        .HasForeignKey("PersoneelsledenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotBargainVbEx.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectenProjectNaam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
